os: linux
dist: xenial

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $TRAVIS_BUILD_DIR/vendor

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - make lint
  - make phpcs
  - make phpmd
  - make phpstan
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - php bin/test-reporter --coverage-report=$TRAVIS_BUILD_DIR/coverage.xml

notifications:
  email: false

